<!-- CRIE UM VETOR COM 10 VALORES NÚMERICOS. EM SEGUIDA, SOLICITE AO USUÁRIO UM NÚMERO (VIA POST PELO HTML) PARA MULTIPLICAR TODOS OS ELEMENTOS DO VETOR. 
O PROGRAMA DEVERÁ EXIBIR O RESULTADO DA MULTIPLICAÇÃO DO NÚMERO DADO PELO USUÁRIO EM TODOS OS ELEMENTOS ARMAZENADOS, E TAMBÉM A SOMA DE TODOS OS ELEMENTOS DO VETOR. -->

<?php

?>
